<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.xlogistx</groupId>
        <artifactId>xlogistx-mvn</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <groupId>org.zoxweb</groupId>
    <artifactId>zoxweb-datastore</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>


    <modules>
        <module>common-datastore</module>
        <module>mongo-legacy</module>
        <module>hibernate</module>
        <module>mongo-sync</module>
        <module>zoxweb-jdbc</module>
        <module>xlogistx-datastore</module>

        <module>h2p-datastore</module>
        <!--        <module>common</module>-->
    </modules>


    <properties>
        <h2.version>2.4.240</h2.version>
    </properties>

    <url>http://maven.apache.org</url>


    <dependencies>


        <dependency>
            <groupId>org.zoxweb</groupId>
            <artifactId>zoxweb-core</artifactId>
            <version>${zoxweb-core.version}</version>
        </dependency>
        <dependency>

            <groupId>com.github.f4b6a3</groupId>
            <artifactId>uuid-creator</artifactId>
            <version>${uuid.gen.version}</version>
        </dependency>


        <dependency>
            <groupId>io.xlogistx</groupId>
            <artifactId>xlogistx-shiro</artifactId>
            <version>${xlogistx.version}</version>
        </dependency>
        <dependency>
            <groupId>io.xlogistx</groupId>
            <artifactId>xlogistx-opsec</artifactId>
            <version>${xlogistx.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-core</artifactId>
            <version>${apache.shiro.version}</version>
        </dependency>

        <dependency>
            <groupId>javax.cache</groupId>
            <artifactId>cache-api</artifactId>
            <version>${javax-cache.version}</version>
        </dependency>

        <dependency>
            <groupId>org.ehcache</groupId>
            <artifactId>ehcache</artifactId>
            <version>${ehcache-org.version}</version>
        </dependency>


        <!--       <dependency>-->
        <!--            <groupId>com.google.code.gson</groupId>-->
        <!--            <artifactId>gson</artifactId>-->
        <!--        </dependency>-->

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>

        <dependency>
            <groupId>commons-logging</groupId>
            <artifactId>commons-logging</artifactId>
            <version>${common.logging.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>


    </dependencies>

</project>